/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2022-12-18 13:51:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.charge;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.lang.*;
import java.text.*;
import java.net.InetAddress;

public final class fastInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1671353233540L));
    _jspx_dependants.put("jar:file:/D:/peace/team01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/peace/team01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.InetAddress");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Ticket Infomation_fastInfo</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("\t* { margin: 0; padding: 0; }\r\n");
      out.write("\tbody, html { width:100%; }\r\n");
      out.write("\tul { list-style:none; }\r\n");
      out.write("\ta { text-decoration: none; }\r\n");
      out.write("\tbutton, input { outline:0; background-color: #333; color:#fff; }\r\n");
      out.write("\t.wrap { width: 100%; clear:both; }\r\n");
      out.write("    .container {display:block; clear:both;}\r\n");
      out.write("    .top {text-align: center;}\r\n");
      out.write("    .notiDiv {display:block; margin: 100px; padding: 100px;background-color: rgb(239, 239, 239);}\r\n");
      out.write("    .tit {font-size :40px; font-weight: 700;}\r\n");
      out.write("    .dotTit {font-size: 28px;}\r\n");
      out.write("    .barList {font-size : 20px;}\r\n");
      out.write("    .buttonDiv {text-align: center; margin: 50px 0;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav aria-label=\"breadcrumb\">\r\n");
      out.write("    <ol class=\"breadcrumb\">\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"#\">이용요금 안내</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item active\" aria-current=\"page\">패스트트랙 요금</li>\r\n");
      out.write("    </ol>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"top\">\r\n");
      out.write("        <h1>패스트트랙 요금</h1>\r\n");
      out.write("        <p>원하는 어트랙션을 누구보다 빠르게 즐기는 프리미엄 서비스!</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <table class=\"table table-bordered\">\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr class=\"table-active\">\r\n");
      out.write("            <th scope=\"col\"><span class=\"tl\">5회권</span><p>30,000원</p></th>\r\n");
      out.write("            <th scope=\"col\"><span>10회권</span><p>50,000원</p></th>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("            \t대상 : 당일 티켓 구매 고객, 연간 이용 고객 (  ※구매 당일 한정, 1인 1매 사용 )<br>\r\n");
      out.write("\t\t\t\t혜택 : 패스트트랙 전용 대기 라인으로 빠르게 탑승<br>\r\n");
      out.write("\t\t\t\t판매처 : 온라인 예매<br>\r\n");
      out.write("\t\t\t\t사용방법 : 패스트트랙 예매 후 패스트트랙 예약 하기에서 예약\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("    <div class=\"notiDiv\">\r\n");
      out.write("        <h4 class=\"tit\">꼭 알아두세요!</h4>\r\n");
      out.write("        <p class=\"dotTit\"><strong>[구매]</strong></p>\r\n");
      out.write("        <p class=\"barList\">1. 본 상품은 '사전 예매' 방식으로 구매하실 수 있으며, 롯데월드 홈페이지에서 구매 가능합니다.<br>\r\n");
      out.write("            ※ 오픈 시간은 현장 상황에 따라 일부 조정될 수 있습니다.<br><br>\r\n");
      out.write("          2. 본 상품은 한정 수량 상품으로, 다른 손님들의 이용 기회를 보장하기 위해 1인 당 최대 4매까지 구매 가능합니다.</p>\r\n");
      out.write("        <p class=\"dotTit\"><strong>[취소 및 환불]</strong></p>\r\n");
      out.write("        <p class=\"barList\">1. 본 상품은 예약 후 미이용시에는 위약금 100%가 부과되며, 아래 경우를 포함하여 당일 취소 및 환불은 불가능합니다.<br>\r\n");
      out.write("            - 개인 사정 등으로 인한 단순 변심<br>\r\n");
      out.write("            - 사전 고지된 운휴 일정 외 예고 없는 손님 안전 목적의 어트랙션 점검<br>\r\n");
      out.write("            - 우천, 강풍 등의 기상 상황 악화로 매직아일랜드 어트랙션 운행 대기<br><br>\r\n");
      out.write("            2. 본 상품은 방문 예정일 전날 23시 59분까지만 취소가 가능하며, 이후에는 예약 취소 및 환불이 불가능합니다. <br>\r\n");
      out.write("            ※ 단, 금융사별 정산 시간에 따라 취소 가능 시간이 상이하니 금융사에 확인하시기 바랍니다.<br><br>\r\n");
      out.write("            3. 본 상품 구매 후 타인에게 재판매하는 행위는 다른 손님의 이용 기회를 제한하는 것으로, 당사의 영업활동 방해에 해당되어 법적 조치 대상이 될 수 있습니다.</p>\r\n");
      out.write("        <p class=\"dotTit\"><strong>[기타]</strong></p>\r\n");
      out.write("        <p class=\"barList\">1. 매직패스 프리미엄 티켓, 밴드 등 파손/훼손/분실 시 이용권 이용 및 재발행이 불가능합니다.<br><br>\r\n");
      out.write("            2. 다음과 같은 어트랙션은 매직패스 프리미엄 사용이 불가합니다.<br>\r\n");
      out.write("            - 유료 시설 : 툼 오브 호러, 거울미로, 문보트<br><br>\r\n");
      out.write("            3. 일부 어트랙션에서는 시설 구조와 상황에 따라 대기시간이 발생할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    <div class=\"buttonDiv\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/charge/tichetInfo.jsp\" type=\"button\" class=\"btn btn-outline-info btn-lg\">티켓 요금 보기</a>\r\n");
      out.write("        <a href=\"\" type=\"button\" class=\"btn btn-info btn-lg\">패스트트랙 예매</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /charge/fastInfo.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path1");
    // /charge/fastInfo.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${request.getContextPath() }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /charge/fastInfo.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("path2");
    // /charge/fastInfo.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
